server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.56.103
    username: leyou
    password: leyou
    virtual-host: /leyou
ly:
  sms:
    accessKeyId: LTAIsncYQYG1Yjhj # 你自己的accessKeyId
    accessKeySecret: aySR4oBRliswLp87rF9gQyy1Izz4MQ # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_133976814 # 模板名称